on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Check if project version is release version
        run:  test "v$(cut -d \" -f 2 metagraph/version.sbt)" = "${{ github.ref_name }}"

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.4.2
        with:
          configuration: ".github/config/changelog.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
        with:
          tagRegex: "v(.*)"
          tagRegexGroup: 1

      - name: Setup Java and scala
        with:
          JAVA_VERSION: openjdk@1.11.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: "./.github/templates/setup_java_and_scala"

      - name: Fetch Dependencies
        shell: bash
        if: steps.coursier-cache.outputs.cache-hit-coursier != 'true'
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        run: |
          cd metagraph
          sbt +update

      - name: Assembly 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd metagraph
          sbt 'currencyL0/assembly;currencyL1/assembly;dataL1/assembly'

      - name: Copy dependencies
        run: |
          cd metagraph
          cp ./modules/l0/target/scala-2.13/elpaca_metagraph-currency-l0-assembly-${{ steps.tagName.outputs.tag }}.jar ./metagraph-l0.jar
          cp ./modules/l1/target/scala-2.13/elpaca_metagraph-currency-l1-assembly-${{ steps.tagName.outputs.tag }}.jar ./currency-l1.jar
          cp ./modules/data_l1/target/scala-2.13/elpaca_metagraph-data_l1-assembly-${{ steps.tagName.outputs.tag }}.jar ./data-l1.jar

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: Elpaca Metagraph Release ${{ steps.tagName.outputs.tag }}
          draft: false
          prerelease: false
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: |
            ./metagraph/metagraph-l0.jar
            ./metagraph/currency-l1.jar
            ./metagraph/data-l1.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
